### ISSUE TITLE
Getting failures running generate

### ISSUE THREAD

**Issue by daluu** [yearbook/extendscript-api-documentation#13]
Wondering if I have missing dependencies or installed node improperly. I forget if I installed via brew or not. But when first ran generate script had to do npm install of the dependencies jade, less, snockets-cli. Once done generate ran but with errors below.

module.js:338
    throw err;
          ^
Error: Cannot find module 'libxmljs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/davidluu/Documents/extendscript-api-documentation/bake.js:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
/usr/local/lib/node_modules/jade/lib/runtime.js:231
  throw err;
        ^
Error: ./docs/index.jade:1
  > 1| doctype 5
    2| html(lang='en', ng-app='ybmDocApp')
    3|   head
    4|     title ExtendScript API

`doctype 5` is deprecated, you must now use `doctype html`
    at Object.Lexer.doctype (/usr/local/lib/node_modules/jade/lib/lexer.js:256:13)
    at Object.Lexer.next (/usr/local/lib/node_modules/jade/lib/lexer.js:900:15)
    at Object.Lexer.lookahead (/usr/local/lib/node_modules/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/usr/local/lib/node_modules/jade/lib/parser.js:102:23)
    at Parser.peek (/usr/local/lib/node_modules/jade/lib/parser.js:79:17)
    at Parser.parse (/usr/local/lib/node_modules/jade/lib/parser.js:117:26)
    at parse (/usr/local/lib/node_modules/jade/lib/index.js:104:21)
    at Object.exports.compile (/usr/local/lib/node_modules/jade/lib/index.js:205:16)
    at renderFile (/usr/local/lib/node_modules/jade/bin/jade.js:227:71)
    at Array.forEach (native)
Warning: missing space before text for line 40 of jade file "./docs/templates/class.jade"
Warning: missing space before text for line 64 of jade file "./docs/templates/class.jade"
Warning: missing space before text for line 85 of jade file "./docs/templates/class.jade"
Warning: missing space before text for line 28 of jade file "./docs/templates/element.jade"
Warning: missing space before text for line 48 of jade file "./docs/templates/element.jade"
Warning: missing space before text for line 69 of jade file "./docs/templates/element.jade"
/usr/local/lib/node_modules/jade/lib/runtime.js:231
  throw err;
        ^
Error: ./docs/templates/index.jade:10
    8| 
    9|   :markdown
  > 10| 
    11|     We at Yearbook Machine make extensive use of the ExtendScript API on a
    12|     daily basis, but found the documentation system difficult to deal with.
    13|     This is our solution to the problem. An attempt at making the ExtendScript

unexpected token "pipeless-text"
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:252:15)
    at Parser.block (/usr/local/lib/node_modules/jade/lib/parser.js:708:25)
    at Parser.tag (/usr/local/lib/node_modules/jade/lib/parser.js:817:24)
    at Parser.parseTag (/usr/local/lib/node_modules/jade/lib/parser.js:738:17)
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:211:21)
    at Parser.parse (/usr/local/lib/node_modules/jade/lib/parser.js:122:25)
    at parse (/usr/local/lib/node_modules/jade/lib/index.js:104:21)
    at Object.exports.compile (/usr/local/lib/node_modules/jade/lib/index.js:205:16)
    at renderFile (/usr/local/lib/node_modules/jade/bin/jade.js:227:71)
    at Array.forEach (native)
mv: rename ./html/index.html to ./html/preprocessed.html: No such file or directory
cat: ./html/preprocessed.html: No such file or directory
rm: ./html/preprocessed.html: No such file or directory

originally had node v0.10.26 installed, upgraded to latest v0.12.0 and tried reinstall the dependent modules and that didn't help. Noticed reinstalled modules with same npm install command gave these warnings:

npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6

I didn't notice observe warnings on initial install, but in both cases, I think they installed ok, but reinstall shows the warnings.

**Comment by undavide** [comment]
Same here – besides, I'm getting tons of errors trying to `node-gyp` the `libxmljs`.
Seems like I'm running a too up-to-date version of npm...
Is there a node and `libxmljs` versions mix which are known to work?
Thank you.

**Comment by wridgers** [comment]
Hey guys, I've managed to get some time to work on this today.

I've fixed these bugs on the `feature/restructure` branch, PR here: https://github.com/yearbook/extendscript-api-documentation/pull/17

It is my aim to merge and release this today. I'll close this issue once it's complete.

**Comment by wridgers** [comment]
Just merged this PR, which should solve this problem. It's much easier to build the docs now!

Let me know if you have any problems.

**Comment by undavide** [comment]
Hi @wridgers, thanks for looking into this!
I'm afraid I'm still have quite some issues... let me try to recap everything.

I've had permission issues with findxml - solved - but it outputs an error because it can't find illustrator.xml (that I don't have - commented out) and especially weird, there's nothing like:

`~/Library/Preferences/ExtendScript Toolkit/4.0/omv*.xml`

at all in my system (even if ESTK is alive an well doing). Commented out that line too.
I've `javascript.xml` and `scriptui.xml` from: 

`/Library/Application Support/Adobe/Scripting Dictionaries CC/CommonFiles` 

and omv.xml (renamed as `photoshop.xml`) from:

`/Library/Application Support/Adobe/Scripting Dictionaries CC/photoshop`.

I've had to delete lines in the `xml/map.json` as well in order to let other python script deal with the lack of indesign and illustrator files.

Eventually `sudo npm run build` completed without errors.
Problem is that the page – I serve it with a python line (`python -m SimpleHTTPServer`) shows like:

![image](https://cloud.githubusercontent.com/assets/5939127/18648246/1d66556a-7eba-11e6-8df0-a9d1a73319a1.png)

I guess because the html template doesn't seem to link `angular.js`, `angular-route.js` and `angular-resource.js`.
I've tried adding them myself in the html yet I'm having other errors firing in the console:

![image](https://cloud.githubusercontent.com/assets/5939127/18648350/8cfc3796-7eba-11e6-846a-6a762abeabae.png)

By the way, the same thing that I see in your website [here](http://yearbook.github.io/esdocs/).

At this point I gave up...
Please let me know, I'm eager to see my freshly backed documentation!

Thank you very much,

Davide

**Comment by wridgers** [comment]
@daluu, No problem, thanks for responding. :)

@undavide, Thanks for the testing and feedback. :)

Do you have Adobe ExtendScript or InDesign installed? You'll need these installed if not. If you're just interested in Photoshop, you did the right thing commenting out the lines in `map.json`. I'll update the `findxml` command so that it's less aggressive when it can't find files.

> Eventually `sudo npm run build` completed without errors.

Just a note, you shouldn't need `sudo` to run this command. You'll probably run into permission errors if you do this. (To clarify, you don't need `sudo` for `npm install` either, otherwise `node_modules` will have the wrong permissions).

Re. the broken website, this is a mistake on my part. These two commits should fix your issues:
3676a12 and e50978c.

Let me know how you get on! Exciting to see someone else getting this running.

**Comment by undavide** [comment]
@wridgers: the ExtendScript Toolkit is installed, still can't find anything like `~/Library/Preferences/ExtendScript Toolkit/4.0/omv*.xml` (nor in the OS Library – I've performed a system-wide search and found only the usual stuff).
Isn't this the same as what's in `/Library/Application Support/Adobe/Scripting Dictionaries CC/CommonFiles`?

To work around ID and IL I've done the tweaking I've mentioned (which are OK), and adding not only `angular*.js` but also `js/controllers/*` in the HTML template made it! If this is what you've fixed in the two latest commits I guess it's OK :-)
Thank you,

Davide

**Comment by wridgers** [comment]
Yup that's what the last two commits fixed. :)

Maybe you need to run ExtendScript Toolkit and open the Object Model Viewer for it to fetch the `omv.xml` files? This is just a guess.

**Comment by undavide** [comment]
The only ESTK related xml I've been able to find is within the app package itself, here:

`/Applications/Adobe ExtendScript Toolkit CC/ExtendScript Toolkit.app/Contents/SharedSupport/Required/defs.xml`

But I'm not sure whether it's the one you mention. Isn't the `javascript.xml` enough? (besides scriptui and photoshop). In other words, `javascript.xml` from the `Scripting Dictionaries CC/CommonFiles` == `ExtendScript Toolkit/4.0/omv*.xml`

Thanks!

**Comment by wridgers** [comment]
Hmm, very strange. Not for me.

`javascript.xml` only has these:

![screen shot 2016-09-20 at 11 31 53](https://cloud.githubusercontent.com/assets/235730/18666843/dcd3824a-7f25-11e6-9221-12232b831c35.png)

I'm not sure what `defs.xml` is. I have it on my system, but it's not very big.

What versions are you using? I only have access to CC 2014 at the moment.

**Comment by undavide** [comment]
That's the very same list I see myself when building with javascript.xml. Then I have: 
![image](https://cloud.githubusercontent.com/assets/5939127/18667388/a9e5a236-7f30-11e6-9b1c-3ecd264483d2.png)
And a long Photoshop list. If that's it, I guess I'm OK.
BTW, CC2015.5 and ESTK from the CC app.

**Comment by wridgers** [comment]
That looks about right then.

> BTW, CC2015.5 and ESTK from the CC app.

This is probably why we can't find the InDesign or Illustrator OMV files. They might be in a different place now... I'll check when I next have access to a machine with these installed.
